### ISSUE TITLE
How to get storeon instance?

### ISSUE THREAD

**Issue by selim13** [storeon/svelte#16]
Lets say I want to dispatch something from a component which doesn't need to subscribe to any state changes. I would directly call `store.dispatch('something')` for this, but currently there is no access to the original storeon instance.

**Comment by distolma** [comment]
Hi, currently there only one way to get `dispatch` function, like described in the README. It can be a design flaw and we can improve API. For example, use array destructuring like on React: `const [count, dispatch] = connect("count")`. I'll be happy if you suggest some ideas about how we improve API.

**Comment by selim13** [comment]
Or object destructuring, this will make it similar to useStoreon:
```
const { dispatch, count } = connect('count')`
const { dispatch } = connect()`
```

Also maybe allow to pass store instance to createSvelteStore (or add another function for this) so one could access store and it's methods directly?
```
export const store = createStore([...]);
export const connect = createSvelteStore(store);
```

**Comment by distolma** [comment]
Object destructuring can be overcomplicated with renaming, so like React hooks, better to use array destructuring.

Passing store to `createSvelteStore` doesn't look natural, better to return `connect` and `store` from this factory function.

**Comment by distolma** [comment]
Fixed https://github.com/storeon/svelte/commit/7e77afd3288d684c341fcbe6453e8ff2dd3985fd
