### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by ai** [storeon/svelte#6]
1. Link to Svetle
2. Link to Size Limit (since there is a different way to calculate size)
3. `npm install storeon-svelte` to make instruction even simpler
4. Fix gap between first description and `How to use`
4. `Storeon Svelte` title to fit other Storeon projects style

**Comment by distolma** [comment]
done

**Comment by ai** [comment]
1. You can remove «Auto-subscription to the store» feature it is not very clear for users.
2. You can tell about the size in a separated sentence, you do not need `<ul>` in this case.
3. You can remove `yarn` example since most of the yarn users can convert npm command to yarn. It will save you space in docs.
