### ISSUE TITLE
Move into Storeon org

### ISSUE THREAD

**Issue by ai** [storeon/svelte#8]
The first step is to enable 2FA for GitHub and for npm login.

Then, give me your npm login.

**Comment by distolma** [comment]
thanks, i`ve enabled 2fa for github and npm. my npm login: @distolma

**Comment by ai** [comment]
:+1: I sent you invites. Ping me when you rename project and make first release by `npx clean-publish --access=public`

**Comment by distolma** [comment]
i renamed and published package https://www.npmjs.com/package/@storeon/svelte

**Comment by ai** [comment]
It will be better to rename GitHub project too under `@storeon` org. It will make easy to user to find this project and it will look like it is official project.

**Comment by distolma** [comment]
Done. I`ve transferred repo to the storeon team but name still 'storeon-svelte' and i have no permission to rename

**Comment by ai** [comment]
You are admin right now and can rename the project

**Comment by distolma** [comment]
Done. The project completely moved to the `storeon` team ⚡️
